name: dreo
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - mamba
  - jupyter
  - numpy=2.1.3
  - numba=0.61.0
  - scipy=1.15.2
  - matplotlib
  - xarray
  - zarr
  - netcdf4
  - pygeogrids
  - dask
  - pip:
    - ascat
    - cadati
    - pynetcf
    - ismn
    - pytesmo==0.17.0
    - fibgrid
    - lxml
    - flake8-nb
